### ISSUE TITLE
DetachedInstanceError: Parent instance <Document at 0x3d23810> is not bound to a Session; lazy load operation of attribute 'parent' cannot proceed

### ISSUE THREAD

**Issue by zopyx** [Kotti/Kotti#187]
My Kotti application consists of a custom content-type and a section where we pull in other data
from a Postgres DB - also on top of SQLAlchemy (but using our own DB connection and DB session).

I am receiving the following error while rendering a view with some data from our tables.
The view is rendered without problem but I see the error on the console.
I am surprised by this error because there is actually no Kotti functionality involved here  - especially no Document.

-aj

```
~/sandboxes/mib.pyramid$ bin/pserve  development.ini 
Starting server in PID 31368.
serving on http://0.0.0.0:5000
2013-01-06 20:50:40,378 ERROR [kotti.views.cache][Dummy-1] <function caching_policy_chooser at 0x2dd1e60> raised an exception.
Traceback (most recent call last):
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/views/cache.py", line 105, in set_cache_headers
    caching_policy = caching_policy_chooser(context, request, response)
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/views/cache.py", line 92, in caching_policy_chooser
    context, request, response)
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/views/cache.py", line 82, in default_caching_policy_chooser
    elif get_user(request) is not None:
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/util.py", line 90, in replacement
    cached_value = cache[key] = func(*args, **kwargs)
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/security.py", line 35, in get_user
    userid = authenticated_userid(request)
  File "/home/macyet/sandboxes/mib.pyramid/eggs/pyramid-1.4-py2.7.egg/pyramid/security.py", line 71, in authenticated_userid
    return policy.authenticated_userid(request)
  File "/home/macyet/sandboxes/mib.pyramid/eggs/pyramid-1.4-py2.7.egg/pyramid/authentication.py", line 88, in authenticated_userid
    callback_ok = self.callback(userid, request)
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/security.py", line 339, in list_groups_callback
    return list_groups(name, context)
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/security.py", line 266, in list_groups
    return list_groups_ext(name, context)[0]
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/util.py", line 90, in replacement
    cached_value = cache[key] = func(*args, **kwargs)
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/security.py", line 297, in list_groups_ext
    for idx, item in enumerate(items):
  File "/home/macyet/sandboxes/mib.pyramid/eggs/pyramid-1.4-py2.7.egg/pyramid/location.py", line 63, in lineage
    resource = resource.__parent__
  File "/home/macyet/sandboxes/mib.pyramid/eggs/Kotti-0.8b1-py2.7.egg/kotti/resources.py", line 246, in __parent__
    return self.parent
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/attributes.py", line 251, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/attributes.py", line 545, in get
    value = self.callable_(state, passive)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/strategies.py", line 497, in _load_for_state
    (orm_util.state_str(state), self.key)
DetachedInstanceError: Parent instance <Document at 0x3d23810> is not bound to a Session; lazy load operation of attribute 'parent' cannot proceed
```

**Comment by mgrbyte** [comment]
Just to say I also see this in a not-found view (where` the context `pyramid.exceptions.HTTPNotFound`)
The master template is looking at `request.user`, which triggers this.
