### ISSUE TITLE
kotti.message.send_email() in a listener

### ISSUE THREAD

**Issue by castaf** [Kotti/Kotti#311]
Hi,

I would send an email when an object was inserted or updated, and if there was an error during the process, I would that the email was not sent.

I have an issue when I use kotti.message.send_email() :

Traceback (most recent call last):
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 55, in resource_timer_handler
    result = handler(request)
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/pyramid_tm/**init**.py", line 82, in tm_tween
    reraise(_exc_info)
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/pyramid_tm/**init**.py", line 70, in tm_tween
    manager.commit()
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/transaction/_manager.py", line 111, in commit
    return self.get().commit()
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/transaction/_transaction.py", line 280, in commit
    reraise(t, v, tb)
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/transaction/_transaction.py", line 271, in commit
    self._commitResources()
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/transaction/_transaction.py", line 417, in _commitResources
    reraise(t, v, tb)
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/transaction/_transaction.py", line 389, in _commitResources
    rm.tpc_begin(self)
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py", line 90, in tpc_begin
    self.session.flush()
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1818, in flush
    self._flush(objects)
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1845, in _flush
    self.dispatch.before_flush(self, flush_context, objects)
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/sqlalchemy/event.py", line 372, in __call__
    fn(_args, *_kw)
  File "/home/fabien/www/wsgi/dev-kotti/Kotti/kotti/events.py", line 210, in _before_flush
    notify(ObjectUpdate(obj, req))
  File "/home/fabien/www/wsgi/dev-kotti/Kotti/kotti/events.py", line 131, in __call__
    results.append(handler(event))
  File "/home/fabien/www/wsgi/dev-kotti/Kotti/kotti/events.py", line 167, in **call**
    results.append(handler(event))
  File "/home/fabien/www/wsgi/dev-kotti/kotti_shop/kotti_shop/subscriptions.py", line 91, in send_notification_on_order_state_update
    party.notifications_folder.add_notification(request=request, template_name=template_name, template_vars=template_vars)
  File "/home/fabien/www/wsgi/dev-kotti/kotti_notify/kotti_notify/resources.py", line 81, in add_notification
    send_email(request=request, recipients=recipients, template_name=template_name, template_vars=template_vars)
  File "/home/fabien/www/wsgi/dev-kotti/Kotti/kotti/message.py", line 155, in send_email
    mailer.send(message)
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/pyramid_mailer/mailer.py", line 185, in send
    return self.direct_delivery.send(_self._message_args(message))
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/repoze/sendmail/delivery.py", line 88, in send
    self.createDataManager(fromaddr, toaddrs, message))
  File "/home/fabien/virtualenvs/dev-kotti/lib/python2.7/site-packages/transaction/_transaction.py", line 156, in join
    Status.ACTIVE, Status.DOOMED, self.status))
ValueError: expected txn status 'Active' or 'Doomed', but it's 'Committing'

Then, for now, I use Mailer.send_immediately() function for workaround. With the use of this function, is the email will be sent when a transaction failed?

Thanks,

Fab.

**Comment by castaf** [comment]
> I'd say it's maybe not expected that the phase that the event handler executes in is this committing state
Maybe it would be relevant to execute event handler just before committing by using the Before-commit hook proposed by transaction (http://zodb.readthedocs.io/en/latest/transactions.html#before-commit-hooks) ?
