### ISSUE TITLE
add_filedepot migration fails with SQL syntax error

### ISSUE THREAD

**Issue by dnouri** [Kotti/Kotti#482]
I get this traceback when I try to run a migration on kottidemo:

```
Upgrading kotti:alembic:
  - upgrading from 1063d7178fa to 814c4ec72f1...
Starting migration of blob data
2015-12-28 03:49:00,130 INFO  [kotti][MainThread] Starting migration of blob data
Files written on disk, saving information to DB
2015-12-28 03:49:00,131 INFO  [kotti][MainThread] Files written on disk, saving information to DB
Traceback (most recent call last):
  File "/www/kottidemo/Kotti/kotti/alembic/env.py", line 26, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/www/kottidemo/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/www/kottidemo/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/www/kottidemo/Kotti/kotti/alembic/versions/413fa5fcc581_add_filedepot.py", line 69, in upgrade
    op.drop_column('files', 'data')
  File "<string>", line 8, in drop_column
  File "<string>", line 3, in drop_column
  File "/www/kottidemo/local/lib/python2.7/site-packages/alembic/operations/ops.py", line 1637, in drop_column
    return operations.invoke(op)
  File "/www/kottidemo/local/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/www/kottidemo/local/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 81, in drop_column
    **operation.kw
  File "/www/kottidemo/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 175, in drop_column
    self._exec(base.DropColumn(table_name, column, schema=schema))
  File "/www/kottidemo/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/www/kottidemo/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/www/kottidemo/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/www/kottidemo/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File "/www/kottidemo/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/www/kottidemo/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/www/kottidemo/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/www/kottidemo/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/www/kottidemo/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) near "DROP": syntax error [SQL: u'ALTER TABLE files DROP COLUMN data']
```

**Comment by disko** [comment]
https://twitter.com/zzzeek/status/784398050060099584

I don't have the time to support this use case, so I'll close the issue.
