### ISSUE TITLE
Failure to start Kotti 

### ISSUE THREAD

**Issue by waleedsaud** [Kotti/Kotti#583]
Failure to start Kotti  when issuing pserve command

```
(venv) vagrant@ubuntu-focal:~/venv$ bin/pserve app.ini 
Traceback (most recent call last):
  File "bin/pserve", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/venv/lib/python3.8/site-packages/pyramid/scripts/pserve.py", line 34, in main
    return command.run()
  File "/home/vagrant/venv/lib/python3.8/site-packages/pyramid/scripts/pserve.py", line 275, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/home/vagrant/venv/lib/python3.8/site-packages/plaster_pastedeploy/__init__.py", line 125, in get_wsgi_app
    return loadapp(
  File "/home/vagrant/venv/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/vagrant/venv/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/home/vagrant/venv/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/vagrant/venv/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 213, in invoke
    app = filter(app)
  File "/home/vagrant/venv/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 171, in filter_wrapper
    return fix_call(context.object,
  File "/home/vagrant/venv/lib/python3.8/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/vagrant/venv/lib/python3.8/site-packages/fanstatic/wsgi.py", line 49, in make_fanstatic
    return Fanstatic(app, injector=injector, **local_config)
  File "/home/vagrant/venv/lib/python3.8/site-packages/fanstatic/wsgi.py", line 33, in Fanstatic
    publisher_middleware = Publisher(LibraryRegistry.instance())
  File "/home/vagrant/venv/lib/python3.8/site-packages/fanstatic/registry.py", line 34, in instance
    cls._instance.load_items_from_entry_points()
  File "/home/vagrant/venv/lib/python3.8/site-packages/fanstatic/registry.py", line 22, in load_items_from_entry_points
    self.add(self.make_item_from_entry_point(entry_point))
  File "/home/vagrant/venv/lib/python3.8/site-packages/fanstatic/registry.py", line 82, in make_item_from_entry_point
    if not entry_point.dist.parsed_version.is_devrelease:
AttributeError: 'Version' object has no attribute 'is_devrelease
```

`

**Comment by waleedsaud** [comment]
Found the fix for it which is to update setuptools
```
vagrant@ubuntu-focal:~/energy$ bin/pip install -U setuptools
Collecting setuptools
  Downloading setuptools-61.3.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 433 kB/s 
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.0.0
    Uninstalling setuptools-44.0.0:
      Successfully uninstalled setuptools-44.0.0
Successfully installed setuptools-61.3.0
```

**Comment by waleedsaud** [comment]
for others to see the fix I reopened it so that it is visible

**Comment by disko** [comment]
Closing, as this is not a Kotti issue.
